### ISSUE TITLE
equalize all ecYeast versions in the repo

### ISSUE THREAD

**Issue by edkerk** [SysBioChalmers/GECKO#101]
As also commented on [Gitter](https://gitter.im/SysBioChalmers/GECKO?at=5ec2f909520b7a38fbdbc03b), while an updated [proteome-constrained ecYeast-GEM ](https://github.com/SysBioChalmers/GECKO/tree/master/models/prot_constrained/ecYeastGEM_prot)is provided with a new release, the [batch version](https://github.com/SysBioChalmers/GECKO/tree/master/models/ecYeastGEM) (and "pre-batch"?) are not updated. This also means that the batch version is based on yeast-GEM 8.1.3 while the proteome-constrained model is based on yeast-GEM 8.3.4.

Each release should come with an updated version of ecYeast-GEM, to facilitate its reuse. Particularly if the proteomics-integrated model is updated, then also an updated batch model should be distributed.

**Comment by edkerk** [comment]
Reply from @BenjaSanchez on [Gitter](https://gitter.im/SysBioChalmers/GECKO?at=5ecd25a7549761730b5b146c):
@edkerk those models are there as an example + checking if changes introduced to the method affect results. For the latest versions of any ecModel the user should always go to https://github.com/SysBioChalmers/ecModels (were you can find ecYeast8.3.4 and a few before that). @IVANDOMENZAIN we should probably clarify this in the GECKO repo

**Comment by BenjaSanchez** [comment]
reopening this to remember to, for consistency, equalizing all ecYeast versions in the repo (probably make them all 8.1.3 for simplicity).
