### ISSUE TITLE
fix: switch UBs from Inf to +1000?

### ISSUE THREAD

**Issue by BenjaSanchez** [SysBioChalmers/GECKO#102]
I've noticed that ecModels give an `unbounded` error in cobrapy (but also sometimes with cobratoolbox/RAVEN), because most upper bounds are defined as `Inf`. @IVANDOMENZAIN is there any specific reason that we chose `Inf` instead of `+1000` for the default upper bound? If none then I can change it throughout the toolbox, to guarantee that ecModels work out of the box without needing any specific edits.

**Comment by IVANDOMENZAIN** [comment]
@BenjaSanchez No I don't remember any specific reason for that, I agree on introducing such fix :)
