### ISSUE TITLE
feat: met/rxn metadata in ecModels

### ISSUE THREAD

**Issue by BenjaSanchez** [SysBioChalmers/GECKO#126]
As mentioned in https://github.com/SysBioChalmers/GECKO/pull/125, currently we are stripping off most metadata associated to reactions and metabolites from ecModels, including metabolite charges, reaction EC numbers, ChEBI/KEGG ids, etc. This was originally done to keep ecModels with minimal information, but we could consider ensuring all these elements get properly preserved, by modifying functions such as [`addEnzymesToRxn.m`](https://github.com/SysBioChalmers/GECKO/blob/master/geckomat/change_model/addEnzymesToRxn.m) and [`addArmReaction.m`](https://github.com/SysBioChalmers/GECKO/blob/master/geckomat/change_model/addArmReaction.m) to copy all original fields. I can see it being beneficial for e.g. mapping things quicker without needing to go back to the original models. @IVANDOMENZAIN what are your thoughts on this?

**Comment by IVANDOMENZAIN** [comment]
I agree on introducing these modifications, ecModels are an extension to the knowledgebase provided by GEMs, so all the original annotation and metadata should be kept.

**Comment by edkerk** [comment]
In GECKO3, the original model information remains intact.
