### ISSUE TITLE
Improve speed of updating database from KEGG 

### ISSUE THREAD

**Issue by mihai-sysbio** [SysBioChalmers/GECKO#140]
Having a poke around [updateDatabases.m](https://github.com/SysBioChalmers/GECKO/blob/devel/geckomat/get_enzyme_data/updateDatabases.m), I see a potential improvement around how the KEGG API is used:

https://github.com/SysBioChalmers/GECKO/blob/6fbc627ca07cf7637cd0a95355ed1e1e1c2ee1f0/geckomat/get_enzyme_data/updateDatabases.m#L71-L92

Currently, as far as I understand, the process is to get a KEGG ID from the model, use the API for that ID

> e.g. http://rest.kegg.jp/list/hsa:7358

, and parse the response. This ends up making many API calls, that take a lot of time.

Instead, I think it would be faster to use the organism API endpoint

> e.g. http://rest.kegg.jp/list/hsa/

, parse the response and then to [intersect](https://www.mathworks.com/help/matlab/ref/double.intersect.html) the IDs from the response with the IDs in the model.

**Comment by edkerk** [comment]
The proposed strategy with `intersect` wouldn't work as the first call uses `/list` to get all gene identifiers, while `/get` is used to download the gene specific information that is needed to make the KEGG database for GECKO, containing gene name, EC number, sequence etc. To my knowledge, this can only be done through repeated API calls.

To somewhat improve this, the replacement [`loadDatabases`](https://github.com/SysBioChalmers/GECKO/blob/143a19decfcba66362801922f1499b2d157908fd/src/geckomat/get_enzyme_data/loadDatabases.m#L97-L98) function now downloads 10 genes at the same time.
