### ISSUE TITLE
Reversible field required when running constrainEnzymes with existing ecModels

### ISSUE THREAD

**Issue by jdietrich3** [SysBioChalmers/GECKO#148]
### Description of the bug:
When running constrainEnzymes on an existing ecModel (e.g. [ecYeastGEM.mat](https://github.com/SysBioChalmers/ecModels/blob/master/ecYeastGEM/model/ecYeastGEM.mat)) and with experimental data, the addRxns function from the RAVEN toolbox gives an error due to the lack of a model.rev field in COBRA models.  I'm pretty new to Github and GECKO, and not sure if this would be easier fixed here in GECKO or in the RAVEN toolbox.

#### Code:
```matlab
constrainEnzymes(ecYeastGEM,[],[],P_tot,prot_IDs,prot_abundances,[],[]);
```

#### Output:
```matlab
Reference to non-existent field 'rev'.

Error in addRxns (line 255)
newModel.rev=[newModel.rev;reversible];

Error in constrainPool (line 27)
        model = addRxns(model,rxnToAdd,1,comp,true);

Error in constrainEnzymes (line 97)
    model = constrainPool(model,~measured,full(fs*Pbase));
```

#### Context

<details>
* RAVEN Toolbox version: 2.4.3  
* GECKO version: 2.0.2  
* cobratoolbox version: 3.1  
* Matlab version: R2017b  
</details>

**I hereby confirm that I have:**
- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/GECKO) for running GECKO
- [x] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already

**Comment by edkerk** [comment]
`rev` field is reconstructed in `makeEcModel`
