### ISSUE TITLE
Save auto-flexibilized enzymes during generate_protModels pipeline

### ISSUE THREAD

**Issue by alinarekena** [SysBioChalmers/GECKO#149]
### Description of the new feature:

`flexibilizeProteins` is called from `constrainEnzymes` when generating proteome-constrained ecModels. In `flexibilizeProteins`, second round of flexibilization of abundances is carried out as part of `generate_protModels` pipeline. The first round of modifications from around lines 124-125 of `generate_protModels`are saved as an output, while those from `flexibilizeProteins` are only shown in command window.

**I hereby confirm that I have:**
- [+] Done this analysis in the `master` branch of the repository
- [+] Checked that a similar issue does not exist already

**Comment by mihai-sysbio** [comment]
@alinarekena thanks for raising this feature request. Would this be something you would find comfortable to implement? There are some instructions regarding this process in the [Contributor guidelines](https://github.com/SysBioChalmers/GECKO/blob/devel/.github/CONTRIBUTING.md).

**Comment by alinarekena** [comment]
@mihai-sysbio thanks for your response. No, I can't do it myself.

**Comment by mihai-sysbio** [comment]
Thanks for letting us know - I'll let @IVANDOMENZAIN take it from here.

**Comment by edkerk** [comment]
In GECKO3 pipeline, `flexibilizeProtConcs` gives `flexData` output.
