### ISSUE TITLE
Optimization of Gecko

### ISSUE THREAD

**Issue by johan-gson** [SysBioChalmers/GECKO#152]
### Description of the new feature:
Introduction of some optimizations for Gecko regarding database handling. No functional changes are introduced.

**I hereby confirm that I have:**
- [x] Done this analysis in the `master` branch of the repository
- [x] Checked that a similar issue does not exist already

**Comment by BenjaSanchez** [comment]
@johan-gson this issue lacks explanation about what "optimizations" are needed. In any case, it is not necessary to open an issue at the same time you are opening a PR that solves it (I believe #153?)

**Comment by johan-gson** [comment]
This issue is not really needed, the info is given in the pull request.

**Comment by johan-gson** [comment]
So, I was developing GeckoLight and discovered that running the first steps of Gecko, getEnzymeCodes and matchKcats, took like 20 minutes to run, which was very annoying for my experiments (and for other people I guess). After a quick discussion with Jens I spent two days optimizing the code, and for human it is now down to less than 2 minutes.

**Comment by mihai-sysbio** [comment]
Interesting insight! I guess there weren't major changes in terms of memory usage?

**Comment by johan-gson** [comment]
No, I don't think so, just a few indexes, which indexes in the order of 10000 items, so that is nothing.

**Comment by mihai-sysbio** [comment]
This issue was resolved through PR #153
