### ISSUE TITLE
enhanceGEM not running

### ISSUE THREAD

**Issue by robertoolivaresh** [SysBioChalmers/GECKO#162]
### Description of the bug:
I am trying to run the enhanceGEM.m file using the yeast model (yeast-GEM.mat) its not working. I am using the actual Gecko version available in github.

Thanks in advance for the help

The error is described in the following output a:

>> [ecModely,ecModel_batchy] = enhanceGEM(modely,'RAVEN','out_yeast.xml')

***************************************************************
   GECKO: Adding enzyme constraints to a genome-scale model
***************************************************************

Getting genome-scale model ready... Done!

==================
Generating ecModel:
==================
Retrieving EC numbers............................................ Done!
Matching kcats............................................ Done!
Adding enzymes to reactions...Error using cellfun
Input #2 expected to be a cell array, was struct instead.

Error in convertCharArray (line 18)
    elseif ~iscell(funcInput) && ~(all(cellfun(@ischar, funcInput)) || all(cellfun(@isstring, funcInput)))

Error in changeRxns (line 68)
equations=convertCharArray(equations);

Error in addArmReaction (line 51)
model = changeRxns(model,rxn,equation,1,comp);

Error in convertToEnzymeModel (line 53)
            eModel  = addArmReaction(eModel,rxnID);

Error in readKcatData (line 38)
eModel = convertToEnzymeModel(model,matchedGenes,uniprots,kcats);

Error in enhanceGEM (line 64)
ecModel = readKcatData(model_data,kcats);

**Comment by edkerk** [comment]
This is a RAVEN-related bug. Will fix this asap (will post here when it's done), for now you can use RAVEN [v 2.6.2](https://github.com/SysBioChalmers/RAVEN/releases/tag/v2.6.2), which was before this bug was introduced.

**Comment by edkerk** [comment]
Fixed since [RAVEN 2.7.4](https://github.com/SysBioChalmers/RAVEN/releases/tag/v2.7.4).
