### ISSUE TITLE
getKcat function does not take enzyme subunits into account

### ISSUE THREAD

**Issue by HettieC** [SysBioChalmers/GECKO#183]
When more than one subunit of an enzyme catalyse a reaction there is a coefficient of n/kcat in the stoichiometric matrix S, but the function 

```function [kcat,rxnIdx,rxnName,MW] = getKcat(ecModel,protein)``` 

only ever uses 

```kcat    = -1./ecModel.S(pIdx,rxnIdx)/3600;```

instead of using 

```kcat    = -n./ecModel.S(pIdx,rxnIdx)/3600;```

where n is the number of enzymatic subunits of the enzyme complex required.

**Comment by Yu-sysbio** [comment]
Hi, just use phosphofructokinase (a complex containing two subunits: Pfk1 and Pfk2) in yeast as an example here. The corresponding reaction in [ecYeast](https://github.com/SysBioChalmers/ecModels/blob/main/ecYeastGEM/model/ecYeastGEM.txt) is: **pmet_r_0886[c] + 4.3268e-07 prot_P16862[c] + 4.3268e-07 prot_P16861[c]  -> s_0394[c] + s_0555[c] + s_0794[c]** 
where the coefficient of each of the subunits (**prot_P16862[c]** and **prot_P16861[c]**) is -1/kcat, and thus you can get kcat for each of the subunits by `-1./ecModel.S(pIdx,rxnIdx)/3600` rather than `-n./ecModel.S(pIdx,rxnIdx)/3600`

**Comment by HettieC** [comment]
When there is one subunit of each that makes sense, but if for example there were 1 subunit of prot_A and 2 subunits of prot_B required I can't see how the function deals with that. This is shown in the example given in section 1.4 of the supplementary material of the 2017 GECKO paper, where you have 
R5/f:  M_2 + **1/kcat** E_3+ **2/kcat** E_4 -> M_4

**Comment by edkerk** [comment]
Section 1.4 is an example with a small toy-model, where indeed the subunit copy numbers are considered. In section 2, the application at genome-scale is described. There, in section 2.4 is mentioned:

> If no further manual data is known, the stoichiometry is assumed to be 1:1 in all cases. 

**Until now (GECKO version 1 and 2), GECKO always assumes a 1:1 stoichiometry in complexes (or 1:1:1, 1:1:1:1 etc.)**, and no functions are available to adjust this (you could do it manually though). However, you can see in for instance #160 and #167 that we are working on considering subunit copy numbers, and `getKcat` should then be modified for this as you describe in your first post, (although the `getKcat` function will largely become unneccessary as we will explicitly mention all reaction-specific kcat values in a separate `model.ec.kcat` vector).

**Comment by HettieC** [comment]
Ah ok thanks for explaining. Just to confirm, does that mean that all of enzyme constrained models in the SysBioChalmers/ecModels repository use a 1:1 (etc) stoichiometry in complexes?

**Comment by edkerk** [comment]
Yes, only from GECKO release 3.0 will these stoichiometries taken into account. And it will be obvious which model is generated from GECKO 3. This will still take a few months to fully implement (together with the rest of GECKO 3).

I'll hereby close this thread.
