### ISSUE TITLE
how to use uniprotConversion.tsv

### ISSUE THREAD

**Issue by HossFir** [SysBioChalmers/GECKO#185]
### Description of the new feature:

I built two ecGEMs for my organism. One is reconstructed in a way that only contains genes id and the other is the BiGG model which has gene annotations ({'sbo', 'ncbigi', 'refseq_name', 'refseq_orf_id'}). It seems that GECKO 2.0 only matched the Kcat and UniProt Database based on the gene id. This would cause missing a lot of Kcat for those GEMs which are reconstructed by only gene names like the BiGG model. So I would be appreciated it if is possible to consider this in the GECKO 3.0, that the Kcat could also be matched by the gene names, probably searching for the 'refseq_orf_id' for the BiGG Model.

**Comment by edkerk** [comment]
GECKO3 has the option to provide a custom table matching the Uniprot and gene identifiers:

https://github.com/SysBioChalmers/GECKO/blob/0b07f29619b96594abbd0a04c0372dad7a1cfa14/src/geckomat/model_adapter/ModelAdapter.m#L26-L43

This is a table where the gene identifiers (first column) are matched to uniprot IDs (second column). Would this be able to resolve the issue you encounter?

**Comment by HossFir** [comment]
> re the gene identifiers (first column) are matched to uniprot IDs (second colum

**Comment by HossFir** [comment]
Sorry, but I cannot figure out how this works!

The issue I encountered is that GECKO pipelines did the Kcats matching based on orf_id (locus names, in my case those that start with slr, sll.)! 
Also, the GPRs of some models are complicated as they have reactions with AND/OR relationships! I know that there is the simplifyGrRules.m that makes the model simpler. I think this was done on the Human GEM with GECKO 3.0.2; therefore, it would be appreciated if you could add simplifyGrRules.m in the protocol!

For more explanation, I added the GEM and the ecModel of my organism:

Original Model:

https://github.com/HossFir/Cyano/blob/main/iJN678.xml

ecModel:

https://github.com/HossFir/Cyano/blob/main/ecIJN.xml

Using GECKO 3, only 13 proteins were matched to the model; those that were started with orf_id (locus names e.g. slr, sll.) and not the gene names!

**Comment by edkerk** [comment]
`simplifyGrRules` has nothing to do with this, and also the presence of OR and AND relationships have nothing to do with matching genes to enzymes.

The issue you encounter is to have the correct gene identifiers in the dataset that is gathered from Uniprot. The Uniprot dataset is used to define enzymes in the model, if GECKO cannot figure out which gene is which enzyme, then no enzyme is added.

In the ModelAdapter, have you tried setting the following setting?

```
obj.params.uniprotIDtype = 'proteome'
obj.params.uniprotID = 'UP000001425'
obj.params.uniprotGeneIdField = gene_primary
obj.params.uniprotReviewed = 0
```

But regardless, the model uses a mixture of gene identifiers that in Uniprot are catalogued as "Gene Names (Primary)" (for instance ndhM) and "Gene Names (Ordered locus)" (for instance slr1623). So with the above setting you will still not match all genes. The *best* solution would be to curate the model to be consistent in its gene annotation.

As a workaround, you could manually define a `uniprotConversion.tsv` file, where you have both type of gene annotations. Shown here for one protein, this should be done for all:

```
ndhM	P74338
slr1623	P74338
```

The relevant information could be gathered for instance [here](https://rest.uniprot.org/uniprotkb/stream?query=taxonomy_id:1111708&fields=accession%2Cgene_primary%2Cgene_oln&format=tsv&compressed=false&sort=protein_name%20asc).

With such a `uniprotConversion.tsv` file, the gene will always be matched to the right uniprot protein identifier.
