### ISSUE TITLE
store model-specific files away from GECKO code

### ISSUE THREAD

**Issue by edkerk** [SysBioChalmers/GECKO#187]
### Description of the new feature:
In GECKO1&2, model-specific files were kept in `databases` and `models` subfolders. I propose that a better approach would be to keep this separate.

1. The GECKO folder should have the GECKO code.
2. The ModelAdapters are where custom parameters and functions are kept.
3. The user can choose themselves where they want to have model-specific files written (and read from).
4. The path to the model-specific files location can be specified in the ModelAdapter.
5. This affects:
    - uniprot database files
    - complex portal database files
    - ec-model files
    - potential log files with statistics around the construction process
    - ... likely other files
6. GECKO can still come with one example, for _S. cerevisiae_ (as was GECKO1&2), but this would be in an `example` subfolder of GECKO, and is not the location where files are written/read by default.

**Comment by ae-tafur** [comment]
Following the conversation.

All this functions need are organism/model specific:
- changeMedia_batch.m
- getModelParameters.m
- manualModifications.m
- removeIncorrectPathways.m
- scaleBioMass.m
- sumBioMass.m
- sumProtein.m

This is organism specific data:

- abs_proteomics.txt
- chemostatData.tsv
- fermentationData.txt
- manual_data.txt
- prot_abundance.txt
- uniprot.tab
 
So the user need to change this functions in GECKO depending on the project or organism he is working on. 

I understand that modelAdapter switch the functions depending what the user needs, but this is and implementation for those what GECKO already have, but what if the user it is working in a model which is not in the adapter function ?

**Comment by johan-gson** [comment]
I in general don't have much opinions when it comes to storage of files. One thing that I think we should keep in mind though is the existence of general solutions, such as the one where the phylogenic id is automatically downloaded and stored in a folder. An alternative would be to automatically download it and store it in a folder specified by the model adapter. I don't have a strong opinion here, although I think the current solution is ok.

**Comment by johan-gson** [comment]
I leave this for you @edkerk and @ae-tafur to decide. I'm happy as long as it works and as long as there is no extra specification needed to be done by the user - the goal is that things should be as automatic and simple as possible for a standard run.

**Comment by edkerk** [comment]
For completion, here is the suggestion by @ae-tafur as written in #180:

> I agree that model-specific files should be stored in an "external" folder. I suggest this structure. 
> 
> <img width="1104" alt="Screenshot 2022-11-30 at 10 01 13" src="https://user-images.githubusercontent.com/39610893/208209553-727987c1-0324-431d-bf13-d28d7a9b0d95.png">
> 
> the idea is that projects folder (can be also call Custom ? ) contains the data/scripts for model-specific files it a path is not defined in getModelParameters.m. 
> 
> getModelParameters.m also includes a path where to store the results ecModel/prot_model, this is usefull when working with git repos locally. 
> 
> I already implemented this approach by using GECKO 2 (in my fork). Maybe it can be implemented for GECKO 3 ?

I hadn't noticed the `src` folder, but that would indeed be good: that folder should be read-only.

**Comment by edkerk** [comment]
> I understand that modelAdapter switch the functions depending what the user needs, but this is and implementation for those what GECKO already have, but what if the user it is working in a model which is not in the adapter function ?

The modelAdapter basically replaces `getModelParameters`. The additional benefit is that it can contain functions, so functions like `scaleBioMass` can be specified and modified there. Of course then the pitfall becomes that the modelAdapter script can get quite long.

**Comment by johan-gson** [comment]
And now I have an opinion :) I would change the name of the project folder to something else, such as ModelSpecificData or something else. A project in my mind is something that is limited in time, budget etc., and typically in our world something that ends with a publication of a paper. Things that live forever (such as these) are not projects. It is a really confusing name.

**Comment by johan-gson** [comment]
Otherwise it looks nice!

**Comment by ae-tafur** [comment]
> > I understand that modelAdapter switch the functions depending what the user needs, but this is and implementation for those what GECKO already have, but what if the user it is working in a model which is not in the adapter function ?
> 
> The modelAdapter basically replaces `getModelParameters`. The additional benefit is that it can contain functions, so functions like `scaleBioMass` can be specified and modified there. Of course then the pitfall becomes that the modelAdapter script can get quite long.

Yes, I think that functions like `scaleBioMass` should be in other file

**Comment by ae-tafur** [comment]
> And now I have an opinion :) I would change the name of the project folder to something else, such as ModelSpecificData or something else. A project in my mind is something that is limited in time, budget etc., and typically in our world something that ends with a publication of a paper. Things that live forever (such as these) are not projects. It is a really confusing name.

I totally agree

**Comment by edkerk** [comment]
One problem I could imagine with this folder structure is that a new GECKO version would overwrite existing content (and if you're not paying attention, you'd include custom data/scripts into a PR that is supposed to change a function in `src` only. In git, we could include the `customData` in `.gitignore` to avoid this. Should it just be that folder? In the current proposal there would be multiple folders that should be ignored?

**Comment by johan-gson** [comment]
Perhaps we should just have one data folder - that is usually how I organize my repos. And a structure below that.

**Comment by ae-tafur** [comment]
> One problem I could imagine with this folder structure is that a new GECKO version would overwrite existing content (and if you're not paying attention, you'd include custom data/scripts into a PR that is supposed to change a function in `src` only. In git, we could include the `customData` in `.gitignore` to avoid this. Should it just be that folder? In the current proposal there would be multiple folders that should be ignored?

The idea is that you have a default folder where to have this. But the user can also defined a different path in `getModelParameters` where to find those custom files. 
 
You can check [here](https://github.com/ae-tafur/GECKO/tree/devel2) and maybe have a better idea of what I proposed.

**Comment by edkerk** [comment]
I'm looking at [this branch](https://github.com/ae-tafur/GECKO/tree/refactor/file-structure) which you seem to have updated more recently. I have a few questions:

- should the content of the `ecModels` folder not also be in the relevant `custom` subfolder?
   - `custom/ecYeastGEM/models/` for instance?
- similar for `data/models/yeast-GEM`, should this not be under `custom/ecYeastGEM/data/` or similar?

Otherwise this seems reasonable. We can specify the specific `custom` subfolder in the `ModelAdapter` as `obj.params.customFolder = fullfile(getGECKOroot, 'custom', 'myNewModel');`

which in `YeastGEMAdapter` would read as `obj.params.customFolder = fullfile(getGECKOroot, 'custom', 'ecYeastGEM');`

Then whenever a model-specific files is read/written, it will do it from this location. Non-model specific files are in the `database` folder, as is the case currently.

The user should modify the ModelAdapter anyway for each model, to have the specific parameters, so there we can leave a comment explaining what this is for (and if the user doesn't change it, it still goes to a separate folder). The user can also specify a folder completely outside of the repo.

Finally, in `.gitignore` we will include all other subfolders in `custom` except for `ecYeastGEM` and `ecHumanGEM`, as we provide those as examples.

**Comment by ae-tafur** [comment]
- The purpose of having `ecModels` folder outside of `custom` is to store the ecModels/prot_models which are the output of GECKO. Then, `custom` contains the input and `ecModels` the output. This is the only reason why I keep two different folders. In any case this are default folders, which can be set by the user to an any path (`parameters.customPath` and `parameters.outputPath`).
- I suggest to keep yeast-GEM in `database` folder because this is the main input to build the ecModel (it will store also human-GEM or any kind of example/default model-GEM that GECKO have ). So, yeast-GEM will not change, but the custom data/scripts can be change it by the user and eventually have different results from GECKO. 
- I think we can keep `modelAdapter` as a default function where the user can just switch to use the default parameters defined for human-GEM, yeast-GEM or other validated model/example in GECKO. 

In order to reduce the number of scripts that user need to adapt for models outside yeast and human, I notice that `sumBioMass` and `sumProtein` are essentially the same. It does not make any sense to have both. So, `sumProtein` will be deprecated together to `manualModifications` as you mention in #189.

**Comment by edkerk** [comment]
> * The purpose of having `ecModels` folder outside of `custom` is to store the ecModels/prot_models which are the output of GECKO. Then, `custom` contains the input and `ecModels` the output. This is the only reason why I keep two different folders. In any case these are default folders, which can be set by the user to an any path (`parameters.customPath` and `parameters.outputPath`).

I'd prefer to have a minimum number of folders where user-specific files and scripts are kept. The user might make many different models for different conditions etc., while all the relevant data is in `custom/$yourModel/data/` and `custom/$yourModel/scripts/`. It would then be convenient to have the models also in `custom/$yourModel/models/`.
- Perhaps `custom` is not the best name? Should it be `user`, `project`, or some alternative?

> * I suggest to keep yeast-GEM in `database` folder because this is the main input to build the ecModel (it will store also human-GEM or any kind of example/default model-GEM that GECKO have ). So, yeast-GEM will not change, but the custom data/scripts can be change it by the user and eventually have different results from GECKO

`yeast-GEM` and `human-GEM` will be examples that will be distributed with GECKO, but they are just that: examples, the GECKO code should work on any model. To demonstrate for users how to organize files etc. for their own model, it would be useful to have the `yeast-GEM` and `human-GEM` files (data, scripts, models, output) organized in the same way as would be the case for any other model. `custom/` will then have subfolders `yeast-GEM` and `human-GEM`, populated with all the required files, and an empty `yourModel` folder where the user is instructed to start putting their own data (for instance a `ModelAdapter` template file to be modified.

> * I think we can keep `modelAdapter` as a default function where the user can just switch to use the default parameters defined for human-GEM, yeast-GEM or other validated model/example in GECKO.

At the moment, users need 
> * I think we can keep `modelAdapter` as a default function where the user can just switch to use the default parameters defined for human-GEM, yeast-GEM or other validated model/example in GECKO.

At the moment, users need to specify a `ModelAdapter` flag for various functions. When start working on a new ec-model will just involve making a custom modelAdapter file, where parameters that are not set are automatically inherited from the generic `ModelAdapter`.

> In order to reduce the number of scripts that user need to adapt for models outside yeast and human, I notice that `sumBioMass` and `sumProtein` are essentially the same. It does not make any sense to have both. So, `sumProtein` will be deprecated together to `manualModifications` as you mention in #189.

Indeed. We might actually deprecate `sumBioMass` as and `scaleBioMass` as well, as (1) for `yeast-GEM` these functions are actually in the [yeast-GEM repo](https://github.com/SysBioChalmers/yeast-GEM/tree/main/code/otherChanges); (2) scaling biomass is not critical to make & analyse ec-models. If the user wants to change the biomass composition, they can make these model-specific changes by themselves. But this sounds like a different topic for a different Issue/PR :).

**Comment by ae-tafur** [comment]
> 

> `yeast-GEM` and `human-GEM` will be examples that will be distributed with GECKO, but they are just that: examples, the GECKO code should work on any model. To demonstrate for users how to organize files etc. for their own model, it would be useful to have the `yeast-GEM` and `human-GEM` files (data, scripts, models, output) organized in the same way as would be the case for any other model. `custom/` will then have subfolders `yeast-GEM` and `human-GEM`, populated with all the required files, and an empty `yourModel` folder where the user is instructed to start putting their own data (for instance a `ModelAdapter` template file to be modified.

What about: 
   - userData
        - data
        - scripts
        - models
        - output

**Comment by edkerk** [comment]
I like `userData`. Would each of these then have model-specific subfolders? `userData/data/yeast-GEM/`? Or should there be one intermediate level `userData/yeast-GEM/data/`? Or for combined for any organism/model?

**Comment by ae-tafur** [comment]
I think it should more for `project`. For example:
    -userData
        - ecYeastGEM
            - data
            - scripts
            - models
            - output 
        - ecHumanGEM
            - data
            - scripts
            - models
            - output

**Comment by ae-tafur** [comment]
I think `userData/ecYeastGEM/{data/scripts/models/output}`, it will be the same for human `userData/ecHumanGEM/{data/scripts/models/output}`

**Comment by edkerk** [comment]
Excellent, let's go for that!

**Comment by mihai-sysbio** [comment]
The [`ecModels` ](https://github.com/SysBioChalmers/ecmodels)repository achieves the same purpose as `userData`. Moreover, by storing also the resulting files when running GECKO2, it provides a way for others to download and use those ready models right away. I would propose to re-visit this topic in [a new issue](https://github.com/orgs/SysBioChalmers/projects/1/views/2?pane=issue&itemId=21014996).

**Comment by edkerk** [comment]
I agree. For the short term, ecModels can ensure it clones a GECKO2 release (we can make a GECKO2 branch), while we go about updating the code to work with GECKO3.
