### ISSUE TITLE
error in Line 48 in the protocol file

### ISSUE THREAD

**Issue by Yu-sysbio** [SysBioChalmers/GECKO#201]
https://github.com/SysBioChalmers/GECKO/blob/db7554625b954e576a30f2f606fa7a7691a08fdb/tutorials/protocol.m#L48

I got the errors below when running the protocol till Line 48, where I just changed Line 47 to `modelRoot = fullfile(findGECKOroot,'userData','yourModel');` What are the reason(s) and solution?

Error using ModelAdapter
Abstract classes cannot be instantiated.  Class 'ModelAdapter' defines abstract methods and/or properties.

Error in ModelAdapterManager.getAdapterFromPath (line 36)
            adapter = feval(adapterClassName);

Error in ModelAdapterManager.setDefaultAdapterFromPath (line 51)
            ModelAdapterManager.setDefaultAdapter(ModelAdapterManager.getAdapterFromPath(adapterPath, addToMatlabPath));

**Comment by ae-tafur** [comment]
Do you create a new folder named  `'yourModel'` in `userData` and create a `*adapter.m` file ?

**Comment by ae-tafur** [comment]
Sorry,I double check, we have a `yourModel` dir. The reason is because `ModelAdapter.m` should not have that name. We already have a file named 'ModelAdapter.m' in `src/geckomat/model_adapter`.
