### ISSUE TITLE
Error applyKcatConstrain

### ISSUE THREAD

**Issue by ae-tafur** [SysBioChalmers/GECKO#205]
I identified an error here:

https://github.com/SysBioChalmers/GECKO/blob/12aeddbee0a48bfe9ebe84c2d3ca621549bc29ac/tutorials/protocol.m#L115

What happen ? 

when `printRxnFormula(model,'r_0226')` this is the output (r_0226 is the ATP synthase mitochondrial reaction):

```
at line 56:
	r_0226	s_0397 + 3 s_0794 + s_1326 	->	s_0437 + 2 s_0799 + s_0807

at line 74:
	r_0226	s_0397 + 3 s_0794 + s_1326 	->	s_0437 + 2 s_0799 + s_0807

at line 99:
	r_0226	s_0397 + 3 s_0794 + s_1326 	->	s_0437 + 2 s_0799 + s_0807
```
At this point is ok, since not kcat constrains have not been applied. 

When `applyKcatConstraints` (line 100, see output below) to the ecModel based on the previous kcatList_DLKcat, not change is observed. But, it is ok, since `r_0226` is not present in the list.

```
at line 100 (DLKcat):
	r_0226	s_0397 + 3 s_0794 + s_1326 	->	s_0437 + 2 s_0799 + s_0807
```

When `applyKcatConstraints` under fuzzy matching (output below), it is observed the expected result. Here, it is ok, since in kcatList_fuzzy it is present 'r_0226'.
```
at line 109 (fuzzy):
	r_0226	s_0397 + 3 s_0794 + s_1326 + 0.18338 prot_P00830 + 0.0973862 prot_P00854 + 0.0194846 prot_P00856 + 0.0901104 prot_P05626 + 0.196145 prot_P07251 + 0.229056 prot_P09457 + 0.0225669 prot_P21306 + 0.0662985 prot_P30902 + 0.114963 prot_P38077 + 0.0259672 prot_P61829 + 0.109197 prot_P81449 + 0.0223829 prot_P81450 + 0.0252142 prot_P81451 + 0.0378581 prot_Q06405 + 0.0569612 prot_Q12165 + 0.43243 prot_Q12233 + 0.0472825 prot_Q12349 	->	s_0437 + 2 s_0799 + s_0807
```
But when merging, the output will depend of the model you set as input 

```
at line 115 (merged):
	

> if uses ecModel from line 100 in selectKcatValue:

        ecModel_merged  = selectKcatValue(ecModel, kcatList_merged);
        ecModel_merged  = applyKcatConstraints(ecModel_merged);
	
        r_0226	s_0397 + 3 s_0794 + s_1326 	->	s_0437 + 2 s_0799 + s_0807

	

> if uses ecModel_fuzzy in selectKcatValue:

        ecModel_merged  = selectKcatValue(ecModel_fuzzy, kcatList_merged);
        ecModel_merged  = applyKcatConstraints(ecModel_merged);

	r_0226	s_0397 + 3 s_0794 + s_1326 + 0.18338 prot_P00830 + 0.0973862 prot_P00854 + 0.0194846 prot_P00856 + 0.0901104 prot_P05626 + 0.196145 prot_P07251 + 0.229056 prot_P09457 + 0.0225669 prot_P21306 + 0.0662985 prot_P30902 + 0.114963 prot_P38077 + 0.0259672 prot_P61829 + 0.109197 prot_P81449 + 0.0223829 prot_P81450 + 0.0252142 prot_P81451 + 0.0378581 prot_Q06405 + 0.0569612 prot_Q12165 + 0.43243 prot_Q12233 + 0.0472825 prot_Q12349 	->	s_0437 + 2 s_0799 + s_0807

```

I think the problem is in `mergeDlkcatAndFuzzyKcats` why not include the `r_0226` in the output?

**Comment by edkerk** [comment]
The reason for this is the default parameters in `mergeDLKcatAndFuzzyKcats`. The fuzzy kcat value from `r_0226` was obtained with a level 2 E.C. wildcard (EC x.x.-.-), By default `mergeDLKcatAndFuzzyKcats` discarded _any_ wildcards. While this might be a reasonable approach for particular models (I understand for human-GEM this makes quite a difference), the default setting of this function should not be that restrictive.

I've fixed this in 0c5b7cee047fe72ef3fbec3ceefd82105dc924bc (and provided a bit more detailed documentation on the meaning of the different input parameters).
