### ISSUE TITLE
genes not found in local UniProt DB (minor)

### ISSUE THREAD

**Issue by Yu-sysbio** [SysBioChalmers/GECKO#210]
Potential minor enhancement for your consideration

https://github.com/SysBioChalmers/GECKO/blob/e97f0e69307582048b2776aa74eab3e98156c694/src/geckomat/change_model/makeEcModel.m#L241

Is it necessary to display (maybe just in the command window) those genes that cannot be found in local UniProt DB and thus not be enzyme-constrained?
Sometimes I am quite curious which genes they are and intend to make them constrained. Or we could tell a solution in the protocol, e.g., compare ecModel.genes vs ecModel.ec.genes.

**Comment by edkerk** [comment]
Good point, I'm actually planning to make it an additional output. It might also be helpful to decide which Uniprot dataset (by taxonomy id or proteome id) to use.
