### ISSUE TITLE
Bug in findMetSmiles.m

### ISSUE THREAD

**Issue by Yu-sysbio** [SysBioChalmers/GECKO#211]
https://github.com/SysBioChalmers/GECKO/blob/e97f0e69307582048b2776aa74eab3e98156c694/src/geckomat/change_model/findMetSmiles.m#L35

If Line 26 `exist(smilesDBfile,'file')` is false, then `metMatch` will be an unrecognized variable, and then error occurs in Line 39.

**Comment by edkerk** [comment]
Well spotted, will fix.

**Comment by edkerk** [comment]
Fixed in #213
