### ISSUE TITLE
Bug in protocol.m Line 88

### ISSUE THREAD

**Issue by Yu-sysbio** [SysBioChalmers/GECKO#212]
https://github.com/SysBioChalmers/GECKO/blob/e97f0e69307582048b2776aa74eab3e98156c694/tutorials/protocol.m#L88

It should be `ecModel.metSmiles = findMetSmiles(ecModel);` ?

**Comment by edkerk** [comment]
This behaviour has change in #208, it is now `ecModel = findMetSmiles(ecModel);`. But yes, protocol.m hadn't been updated yet.
