### ISSUE TITLE
Error using runDLKcat (line 180)

### ISSUE THREAD

**Issue by Yu-sysbio** [SysBioChalmers/GECKO#216]
Maybe we should have a troubleshooting for this error that I met using `runDLKcat();`:

> [33mYou are using pip version 19.0.3, however version 23.0.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command. [0m
> Error using runDLKcat (line 180)
> Unable to install pipenv

As suggested I upgraded pip by running `pip install --upgrade pip` on Mac terminal, but got the same error again.
I checked pip version by running `pip -V`, it showed `pip 23.0.1 from /xxx...xxx/python3.9/site-packages/pip (python 3.9)`. This means that the pip that I upgraded is not the same as runDLKcat found. So the reason could be that there are multiple python/pip paths in my computer.

In this case, what is the solution?

**Comment by Yu-sysbio** [comment]
I think this could be addressed by setting the input of the function `runDLKcat`:

> pythonPath = '/Users/xxx...xxx/bin/python3';
> pipPath = '/Users/xxx...xxx/bin/pip3';

then I met 

> Error using runDLKcat (line 176)
> After installing pipenv, it cannot be found in the PATH

**Comment by edkerk** [comment]
So if I understand, you set `pythonPath` and `pipPath` but you still got an error?

**Comment by feiranl** [comment]
> So if I understand, you set `pythonPath` and `pipPath` but you still got an error?

Yes

**Comment by mihai-sysbio** [comment]
It sounds like the operating system has multiple Python versions installed. Assuming it's macOS, [here are some potential solutions ](https://stackoverflow.com/questions/64362772/switching-python-version-installed-by-homebrew). At this stage a person focused on reproducibility would recommend using a Docker image to package the DLkcat dependencies.

**Comment by ae-tafur** [comment]
solution proposed in #226.
