### ISSUE TITLE
feat: improve main README

### ISSUE THREAD

**Issue by mihai-sysbio** [SysBioChalmers/GECKO#221]
### Description of the new feature:

The main README file should be updated:
- [x] ~expand the clarification of the differences between `geckomat` and `geckopy` (especially that these are likely to have diverged even more)~
- [x] add link to tutorials from Readme
- [x] ~update `Contributors` section~
- [x] remove `Last update` date
- [x] either remove TravisCI label, or create a new issue to fix the CI pipeline
- [x] add Zenodo integration and add a Zenodo label
- [x] point to Protocol.m, users may not know the protocol is stored in `tutorials`
- [x] document the branch structure as defined in #227 in the Development Guidelines, and link to this from the README 
- [x] document the deletion of `geckopy` in #259 
- [x] replace `readthedocs` with `gh-pages`

**Comment by edkerk** [comment]
Good point, README will be overhauled. It should also mention GECKO2 as well as GECKO3, with GECKO2 on a separate branch.

**Comment by Yu-sysbio** [comment]
In practice, we should also friendly guide users, e.g. reviewers, who might be not familiar with GitHub, to GECKO3 rather than the previous versions.

**Comment by mihai-sysbio** [comment]
While I am in support of that @Yu-sysbio, I still wonder how do deal with the `geckomat` vs `geckopy` conundrum.

**Comment by edkerk** [comment]
Leave out `geckopy` until it is refactored. The current protocol is focusing on MATLAB.

**Comment by mihai-sysbio** [comment]
Personally, I am fine with whatever decision regarding `geckopy`, but wanted to highlight that GECKO3 is only superseeding the Matlab versions of GECKO. Therefore, setting up a clear README is less straightforward that I'd wish.

**Comment by feiranl** [comment]
Also point to Protocol.m, users may not know the protocol is stored in tutorials.

**Comment by mihai-sysbio** [comment]
> Also point to Protocol.m, users may not know the protocol is stored in tutorials.

Great point @feiranl, I've added this to the issue checklist.

**Comment by mihai-sysbio** [comment]
With #326 merged, this issue is fully resolved and will therefore be closed.
