### ISSUE TITLE
fix: inconsistencies in `userData` folder

### ISSUE THREAD

**Issue by mihai-sysbio** [SysBioChalmers/GECKO#222]
### Description of the bug:

This issue is meant to cover all fixes for the `userData` folder that are not related to code, as they are in the `devel3` branch:
- [x] In each userData subfolder, all folders (code, data, models, output) should be present
- [x] the Readmes should be written in markdown format
- [x] there should be only 1 readme for each subfolder in `userData`, e.g. the file `userData/ecHumanGEM/data/Data files go here.txt` should not exist, and instructions for how to use this should be either in the tutorial or in a new file `userData/ecHumanGEM/README.md`

**Comment by mihai-sysbio** [comment]
I propose to pause any work on this issue until arriving to a plan regarding [this](https://github.com/orgs/SysBioChalmers/projects/1/views/2?pane=issue&itemId=21014996).

**Comment by edkerk** [comment]
No, the format of these folders should be decided*. The README text can be changed/updated later, but the files that are required and mentioned in the protocol should have their allocated location and name.

*How are the subfolders inconsistent? I see that README and similar files (readme.txt, Data files go here.txt etc.) are somewhat differently formatted, and not all (empty) folders are present (yet), but otherwise the structure is the same?

- [ ] In each userData subfolder, all folders (code, data, models, output) should be present, each with at least a small README.md.

**Comment by mihai-sysbio** [comment]
Thanks for the clarifying question @edkerk, indeed that is what I meant by inconsistent, so I have updated the issue description.
Regarding the README files, I would propose at most 1 such file instead of one per subfolder (code, data, etc).

My proposal to pause the work on this issue was more about the presence of the `userData` folders for existing models which overlaps somewhat with that exists in `ecModels`, for example [userData/ecYeastGEM/output](https://github.com/SysBioChalmers/GECKO/tree/devel3/userData/ecYeastGEM/output) and [ecYeastGEM/mode](https://github.com/SysBioChalmers/ecModels/tree/main/ecYeastGEM/model), especially that for the generation of enzyme constrained models [versioning of the dependencies is required](https://github.com/SysBioChalmers/ecModels/blob/d0deca74b5b1ecebab9b7b091888f3d521bf618c/config.ini#L1-L43).

**Comment by mihai-sysbio** [comment]
Update: for a simpler user experience, both `ecHumanGEM` and `ecYeastGEM` will be provided as examples in this folder. Therefore, the work to resolve this issue has been resumed. However, before continuing to add (many) more examples, the integration with the `SysBioChalmers/ecModels` repository will be discussed and resolved.

**Comment by edkerk** [comment]
GECKO provided `userData` folders are consistent. Integration with `SysBioChalmers/ecModels` is a separate concern.
