### ISSUE TITLE
GitHub Action that runs core function tests with each PR

### ISSUE THREAD

**Issue by edkerk** [SysBioChalmers/GECKO#223]
### Description of the new feature:
Similar as is done for instance in [RAVEN](https://github.com/SysBioChalmers/RAVEN/blob/main/.github/workflows/testing.yml), there should be a GitHub Action that runs unit tests with each PR.

The code should:
- [x] Clone the latest RAVEN release & run `checkInstallation` (it comes with glpk solver, which is enough for the tests, so no further settings are required).
- [x] Run `GECKOInstaller.install` from the GECKO main root.
- [x] Run `runtests('geckoCoreFunctionTests')`.
- [x] Add the output from `runtests` as a comment in the PR.
  - The output from `checkInstallation` does not need to be shown.

**Comment by mihai-sysbio** [comment]
Just a heads up, such a GH Action will fail for all PRs that are not based GECKO3 (currently `devel3`).

**Comment by mihai-sysbio** [comment]
This issue has been completed by merging #225.
