### ISSUE TITLE
protocol.m should be updated to fit the latest code changes

### ISSUE THREAD

**Issue by ae-tafur** [SysBioChalmers/GECKO#236]
This line mentions that to create a light model, you can set the last input to true, however, it should be the second.

https://github.com/SysBioChalmers/GECKO/blob/6c0dae90306810fdbd9501109f9b43a967a00646/tutorials/protocol.m#L64

makeEcModel usage is: 

`[model, noUniprot] = makeEcModel(model, geckoLight, modelAdapter)`

Then this line should be 

`makeEcModel(...,true,...)`

**Comment by edkerk** [comment]
I'm sure there are more cases :)

**Comment by edkerk** [comment]
Done in #252.
