### ISSUE TITLE
use of `getSpontaneousReactions`

### ISSUE THREAD

**Issue by mihai-sysbio** [SysBioChalmers/GECKO#238]
### Description of the bug:

The function `getSpontaneousReactions` in [`yourModelAdapter`](https://github.com/SysBioChalmers/GECKO/blob/6c0dae90306810fdbd9501109f9b43a967a00646/userData/yourModel/yourModelAdapter.m#L111-L118) and [`YeastGEMAdapter`](https://github.com/SysBioChalmers/GECKO/blob/6c0dae90306810fdbd9501109f9b43a967a00646/userData/ecYeastGEM/YeastGEMAdapter.m#L106-L113) has to be revised:
- [x] remove TO DOs
- [x] clarify documentation
- [x] purge all references to Human-GEM (a different model than these adapters expect)

**Comment by edkerk** [comment]
Addressed in #252
