### ISSUE TITLE
Bug detected in findMetSmiles for reconstructing E. coli ecModel

### ISSUE THREAD

**Issue by Yu-sysbio** [SysBioChalmers/GECKO#239]
Reported by @feiranl and I also reproduced the same issue, see below:

Using iML1515 as the starting model, when running to the step `ecModel = findMetSmiles(ecModel)`, it increases to 25% and then stays there -- no error occurs but this number never increases.

> Check for local SMILES database... not found.
> Querying PubChem for SMILES by metabolite names...  25% complete

**Comment by edkerk** [comment]
Can you attach the ecModel as .mat file here, to be able to quickly reproduce the problem?

**Comment by edkerk** [comment]
I cannot replicate this. I think this should only hang if there is problems with the internet connection (it will just keep on retrying). Could you retry, and if it hangs again, press the _Pause_ button, and when paused, click on the _Step Out_ button until you're in the `findMetSmiles` function. Then, run the function step-wise with the _Step_ button and see if it indeed hangs when running `webread`?

**Comment by feiranl** [comment]
I tried, hangs again, and it paused at line 64 `catch exception`, still part of the webread. But if you run that successfully, maybe it is our network connection from Shenzhen. Is that possible to give an instruction to user how to run that themselves beyond the GECKO part?

**Comment by edkerk** [comment]
It involves an API call for each metabolite, so not that straightforward to instruct how to download this manually. But currently `smilesDB.tsv` is only written once the function is done, instead it could write a new line after each succesful call, which would at least avoid having to restart from scratch. I'll refactor a bit and let you know when I have something to test.

**Comment by Yu-sysbio** [comment]
@edkerk Could you check if this file is the same as what you obtained?
[smilesDB.tsv.zip](https://github.com/SysBioChalmers/GECKO/files/10835306/smilesDB.tsv.zip)

**Comment by edkerk** [comment]
No, that file is incorrect. But I've now managed to replicate the problem and will push another fix.
