### ISSUE TITLE
fix-more user-friendly for function output

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/GECKO#240]
It is better to give a display as output to inform user where the file has been stored and also in the description of each function.
This suggestion applies to every function with new files stored.
Expected format:
1. Run `>> writeDLKcatInput(ecModel);`
Display `The DLKcatInput.tsv has been stored in  'path'` in the command window

2. add the path and name in the function description.
function writtenTable = writeDLKcatInput(model, ecRxns, modelAdapter, onlyWithSmiles, filename, overwrite)
% writeDLKcatInput
%   Prepares the input for DLKcat, and writes it to data/DLKcat.tsv
%   in the obj.params.path specified in the ModelAdapter.
%
% Input:
%   model           an ec-model
...
% Output:
%   writtenTable    The table written, mainly to be used for testing purposes. **Default file is stored in (here is the default path) with the name ...**

**Comment by edkerk** [comment]
Addressed in #264
