### ISSUE TITLE
makeEcModel/loadDatabase does not inform if UniProt file already exists

### ISSUE THREAD

**Issue by Yu-sysbio** [SysBioChalmers/GECKO#241]
The function `makeEcModel` will detect whether there is a `uniprot.tsv` file, if there is then it will not download. I do not think it is a good idea to have such a detection if one encounters below:

I ran `makeEcModel` for the first time and got an error as it downloaded a wrong `uniprot.tsv` file e.g., caused by wrong uniprotID that I set in the adapter file. Then I realised this wrong uniprotID and corrected it in the adapter file, and then re-ran `makeEcModel`, but I still got the same error.
I know this is because I did not remove the already existing `uniprot.tsv` file that was downloaded based on that wrong uniprotID, but the users would hardly notice this, and might always fail.

Do you have any solution?

**Comment by edkerk** [comment]
I cannot think of anything satisfactory, except from explicitly documenting that existing file is not overwritten, both in the function and when this is discussed in the protocol.

**Comment by edkerk** [comment]
I'll refactor `makeEcModel` to throw a more detailed warning if its `noUniprot` output structure is not empty (and the user might want to try other Uniprot IDs).

**Comment by edkerk** [comment]
Done in https://github.com/SysBioChalmers/GECKO/pull/230/commits/1f99fb038aac1a0c7f6a58ab7b355658eab4afaf
