### ISSUE TITLE
help: Uniprot does not contain same gene annotation as model

### ISSUE THREAD

**Issue by Yu-sysbio** [SysBioChalmers/GECKO#242]
Just report that I cannot find any gene ID type in [UniProt](https://www.uniprot.org/uniprotkb?facets=reviewed%3Atrue&query=Escherichia%20coli%20%28strain%20K12%29) that perfectly matches with model.genes in iML1515 model.

**Comment by edkerk** [comment]
It is similar to human-GEM, where additional conversion is done with `getUniprotCompatibleGenes` in its model adapter file. Briefly, the user should provide a conversion table. This should be a bit more documented than is now the case.

**Comment by edkerk** [comment]
I notice that KEGG seems to have both gene identifiers (https://www.genome.jp/entry/eco:b2551), (a) Uniprot in Other DBs, while (b) the KEGG is the same as in iML1515. A function could be written around this.

**Comment by Yu-sysbio** [comment]
While this could be moved to Post-submission, I am afraid that the user cannot reconstruct an ecModel for E. coli, which is the most likely organism to test our protocols.
I am wondering if it is needed to take short-term action: like yeast, we also provide an `E. coli adapter` and `data` folder, where the `uniprot` file needs to be provided, which should be manually adjusted, and other data files are not so necessary.

**Comment by edkerk** [comment]
Ok, looking into this

**Comment by mihai-sysbio** [comment]
If the easiest solution would be to make some minor modifications to the E.coli model, then I'd recommend using https://github.com/haowang-bioinfo/Ecoli-GEM. It is essentially _i_ML1515 in standard-GEM form, so any changes that are done will be transparent.

**Comment by edkerk** [comment]
It's not about just the _E. coli_ model, it is about any model with non-matching gene identifiers. #252 and text in the protocol now address this.
