### ISSUE TITLE
Bug detected using getECfromGEM

### ISSUE THREAD

**Issue by Yu-sysbio** [SysBioChalmers/GECKO#246]
I used `ecModel = getECfromGEM(ecModel)` to gather EC numbers with the ecModel that I provided [there](https://github.com/SysBioChalmers/GECKO/issues/239#issuecomment-1445113235).

Then I ran `kcatList_fuzzy  = fuzzyKcatMatching(ecModel)` but got:

> Index exceeds the number of array elements (3).
> 
> Error in fuzzyKcatMatching>iterativeMatch (line 223)
>             EC{k}    = [EC{k}(1:dot_pos(4-wild_num)) wc_text(1:2*wild_num+1)];
> 
> Error in fuzzyKcatMatching (line 170)
>             [kcats(i), kcatInfo.info,kcatInfo.stats] = iterativeMatch(EC,substrates{i},substrCoeffs{i},i,KCATcell,...

I guess the reason could be the format of EC numbers in the model does not match the code that reads them?

**Comment by edkerk** [comment]
The problem is that some EC numbers are incorrectly formatted, e.g. `ecModel.eccodes{63} = '2.7.1.11;2.7.1'`, where the second EC number has 3 sets of digits instead of 4. (A proper way to indicate a wildcard is: 2.7.1.-). These incorrect should be manually corrected in model.eccodes, before running getECfromGEM. Fix on its way

**Comment by Yu-sysbio** [comment]
Sorry this seems to be not yet addressed.

I still got `2.7.1.11;2.7.1` in `ecModel.ec.eccodes`, which again led to the error that I reported previously.

**Comment by edkerk** [comment]
Will look into this. Somewhere else you provided the model adapter but I cannot find it anymore, could you please upload or link to it here?

**Comment by Yu-sysbio** [comment]
> Will look into this. Somewhere else you provided the model adapter but I cannot find it anymore, could you please upload or link to it here?

Here it is 
[iML1515Adapter.m.zip](https://github.com/SysBioChalmers/GECKO/files/10880074/iML1515Adapter.m.zip)

**Comment by edkerk** [comment]
The problematic EC number you mention is in PFK_3, and running `getECfromGEM` now throws a warning about this:

![image](https://user-images.githubusercontent.com/7326655/222844542-72b9dcc0-c721-4507-847b-04bd3a62442b.png)

But perhaps the best behaviour would not to throw a warning and still populate `ecModel.ec.eccodes`, but rather throw an error instead.

**Comment by Yu-sysbio** [comment]
Throw a warning just like this and do not populate EC numbers for these reactions. By doing so there will be no error in the `fuzzyKcatMatching` step.

**Comment by edkerk** [comment]
This behaviour is implemented in #252: model is not populated with eccodes if invalid codes are found.
