### ISSUE TITLE
bug for applyComplexData for rat-GEM

### ISSUE THREAD

**Issue by feiranl** [SysBioChalmers/GECKO#249]
### Description of the bug:

As reported by external user @yanghong-bio, the search for complex data of rat is not working as we assumed. 

#### Current behavior:

![IMG_0502](https://user-images.githubusercontent.com/32157802/221905965-af224798-0a54-444e-84ef-ae20c415526c.JPG)

#### Reproducing these results:
[ecrat.mat.zip](https://github.com/SysBioChalmers/GECKO/files/10852246/ecrat.mat.zip)
```matlab
% If you worked on matlab, paste your code here
```

```python
# If you worked on python, paste your code here
```

**Comment by ae-tafur** [comment]
Can you share the .json file dowloaded with the `getComplexData` ?

**Comment by yanghong-bio** [comment]
[ComplexPortal.json.zip](https://github.com/SysBioChalmers/GECKO/files/10853389/ComplexPortal.json.zip)
