### ISSUE TITLE
Bug: Filter proteomics only return one column, despite there are 3 conditions

### ISSUE THREAD

**Issue by ae-tafur** [SysBioChalmers/GECKO#250]
At this point filtering proteomics data contains many columns as many conditions, but this line only returns one column. This because the index inside parenthesis it is only for rows, must be` filtAbund(m,n)`,  

https://github.com/SysBioChalmers/GECKO/blob/1710a9861a60249207d547585cc96581e0ece18b/src/geckomat/utilities/integrate_proteomics/loadProtData.m#L144

Then, this line should be:

`protData.abundances = filtAbund(notAllNan, :);`

to return one column per condition

**Comment by edkerk** [comment]
And line 140

https://github.com/SysBioChalmers/GECKO/blob/1710a9861a60249207d547585cc96581e0ece18b/src/geckomat/utilities/integrate_proteomics/loadProtData.m#L140

should be

`filtAbund(:,i) = mean(condAbund,2,'omitnan');`

right?

**Comment by ae-tafur** [comment]
> right?

You are right
