### ISSUE TITLE
feat: getStandardKcat in model without subSystems

### ISSUE THREAD

**Issue by edkerk** [SysBioChalmers/GECKO#258]
If a model has no subSystems, `getStandardKcat` should not attempt to calculate subSystem-specific kcat values, but just use a generic standard kcat for all reactions it is trying to fill.

**Comment by ae-tafur** [comment]
> If a model has no subSystems, `getStandardKcat` should not attempt to calculate subSystem-specific kcat values, but just use a generic standard kcat for all reactions it is trying to fill.

Do you mean jump to assign the kcat value with standard values and avoid the calculation of subSystem-specific kcats values ?

**Comment by edkerk** [comment]
Indeed, not all models necessarily have subSystems assigned. So instead of not being able to function at all, it would at least be good to enable filling with standard values. Perhaps have a 1-line message to state "No subSystem-specific kcat values can be calculated" or similar.

**Comment by ae-tafur** [comment]
I agree, are you doing this ?

**Comment by edkerk** [comment]
Nopes :), I'm finishing the manuscript at the moment.

**Comment by ae-tafur** [comment]
I will do so
