### ISSUE TITLE
Bug detected in applyComplexData (line 77)

### ISSUE THREAD

**Issue by Yu-sysbio** [SysBioChalmers/GECKO#262]
In E.coli case I got the error below

> Undefined function 'height' for input arguments of type 'struct'.
> 
> Error in applyComplexData (line 77)
>         for j = 1:height(complexData)

Here I attached [ComplexPortal.json.zip](https://github.com/SysBioChalmers/GECKO/files/10877331/ComplexPortal.json.zip)

**Comment by ae-tafur** [comment]
I load this file by using `applyComplexData` and it does not generate and error. Which Matlab version do you have ?

**Comment by Yu-sysbio** [comment]
2019b

**Comment by ae-tafur** [comment]
> 2019b

Probably this is the problem, can you please replace in your code line 77 with this, to test if this work, 
> `for j = 1:size(complexData,1)`

**Comment by Yu-sysbio** [comment]
Now it works. Thanks!
What shall we do to fix this then?

**Comment by ae-tafur** [comment]
I will commit immediately the solution
