### ISSUE TITLE
Bug: Looks for the taxonomically closest organism for matching the Kcats

### ISSUE THREAD

**Issue by HossFir** [SysBioChalmers/GECKO#277]
Description: There was an issue in fuzzyKcatMatching.m when it searches BRENDA for the closest relative organism when the Kcat is unavailable.

The type of error was:
The logical indices contain a true value outside of the array bounds.

I commented the line 493 to skip the issue.

https://github.com/SysBioChalmers/GECKO/blob/ea9e2ef56673f50b764a183fbe1a6d746f64cff3/src/geckomat/gather_kcats/fuzzyKcatMatching.m#L493
https://github.com/SysBioChalmers/GECKO/blob/ea9e2ef56673f50b764a183fbe1a6d746f64cff3/src/geckomat/gather_kcats/fuzzyKcatMatching.m#L357
https://github.com/SysBioChalmers/GECKO/blob/ea9e2ef56673f50b764a183fbe1a6d746f64cff3/src/geckomat/gather_kcats/fuzzyKcatMatching.m#L316
https://github.com/SysBioChalmers/GECKO/blob/ea9e2ef56673f50b764a183fbe1a6d746f64cff3/src/geckomat/gather_kcats/fuzzyKcatMatching.m#L214
https://github.com/SysBioChalmers/GECKO/blob/ea9e2ef56673f50b764a183fbe1a6d746f64cff3/src/geckomat/gather_kcats/fuzzyKcatMatching.m#L173

**Comment by edkerk** [comment]
Would you be able to share the ecModel so that we can try to replicate the problem? This part of the code has been unchanged since GECKO2, so it _should_ not suddenly have a bug.

**Comment by HossFir** [comment]
Sure! This is the ecModel for my organism:

[eciHK_fv.zip](https://github.com/SysBioChalmers/GECKO/files/11018751/eciHK_fv.zip)

**Comment by edkerk** [comment]
I cannot replicate the error. What did you specify as `obj.params.org_name` in the ModelAdapter? And what MATLAB version are you running?

**Comment by HossFir** [comment]
For GECKO 2, I followed the protocol given and downloaded the Prot_abundances from PaxDb and also retrieve Kcat values from BRENDA.
Using GECKO 3, I just set all these automatically in the ModelAdapter.m.

**Comment by edkerk** [comment]
> obj.params.org_name = 'synechocystis sp. PCC 6803'

The issue arose because there are multiple KEGG entries with the same species name ([syn](https://www.genome.jp/kegg-bin/show_organism?org=syn) and [syz](https://www.genome.jp/kegg-bin/show_organism?org=syz)). Is resolved in #289.

Regarding the number of proteins included, this is not related to PaxDB nor BRENDA, but really the data gather from Uniprot. This is indeed different between the GECKO versions, but you can open a separate Issue for this if desired.
