### ISSUE TITLE
Bug: check if DLKcat.tsv has actually been run through DLKcat

### ISSUE THREAD

**Issue by HossFir** [SysBioChalmers/GECKO#278]
@edkerk 
Description:

I think this line should be uncommented. Otherwise, the Kcats found in the DLKcat.tsv were equal to NaN. (it was previously uncommented in the previous GECKO 3.0.0).

https://github.com/SysBioChalmers/GECKO/blob/ea9e2ef56673f50b764a183fbe1a6d746f64cff3/protocol.m#L102

**Comment by edkerk** [comment]
> Otherwise, the Kcats found in the DLKcat.tsv were equal to NaN.
Otherwise DLKcat does not run, and `DLKcat.tsv` is just the original input file. Will implement a check for this, and uncomment that line (which was commented ou to avoid Docker starting every time during testing).
