### ISSUE TITLE
getStandardKcat assigns protein costs to pseudo-reactions

### ISSUE THREAD

**Issue by Yu-sysbio** [SysBioChalmers/GECKO#280]
This function [getStandardKcat](https://github.com/SysBioChalmers/GECKO/blob/ea9e2ef56673f50b764a183fbe1a6d746f64cff3/src/geckomat/gather_kcats/getStandardKcat.m) assigned protein costs to many pseudo-reactions in my model, e.g.,Biomass, NGAM etc. 
What do you suggest to avoid this?

**Comment by ae-tafur** [comment]
Your model in ecModel.rxnNames contains the word "pseudoreaction" ? 

If not, this can be the reason because why it happens.

A quick solution is to add this reactions in the adapter model method 'getSpontaneousReactions'

**Comment by Yu-sysbio** [comment]
No, ecModel.rxnNames does not contain "pseudoreaction". 
While this is not a bug and will not cause any error, it would result in an ecModel with incorrect protein costs if the conventional GEM does not contain the pseudoreaction information.

It is very necessary to indicate somewhere in the protocol: before running getStandardKcat, please ensure to either include "pseudoreaction" in the rxnNames field of the starting model or add the reactions that you do not want to assign pseudo protein costs in the adapter to avoid this issue.

**Comment by edkerk** [comment]
This will be explained in the protocol, plus a custom `data/nonEnzymeRxns.tsv` file can be specified, which `getStandardKcat` will try to read and if it exists, it will use it to exclude those reactions by their reaction identifier. So this is model-specific.
