### ISSUE TITLE
New feature sensitivityTuning

### ISSUE THREAD

**Issue by Yu-sysbio** [SysBioChalmers/GECKO#285]
By running `[ecModel, tunedKcats] = sensitivityTuning(ecModel)` on my model, I got the error below:

> Iteration 1: Growth: 
> The logical indices contain a true value outside of the array bounds.
> 
> Error in sensitivityTuning (line 75)
>         drawFluxes(drawRxns) = res.x(drawRxns);

I am wondering if we could list potential reasons and solutions for the user.

**Comment by edkerk** [comment]
Can you post *.mat with the ecModel and model adapter, to replicate what it encounters?
