### ISSUE TITLE
ec.source in getStandardKcat

### ISSUE THREAD

**Issue by Yu-sysbio** [SysBioChalmers/GECKO#286]
`getStandardKcat` allows to assign kcats for reactions without any associated genes, and then mark in `.ec.source` with `'standard'`.
It can also assign kcats for the reactions with genes but not assigned kcats by previous steps e.g. BRENDA and DLKcat, but the `.ec.source` is marked with empty, i.e. `''`. I am wondering if this should also be marked with `'standard'`.

Given that `'brenda'` and `'dlkcat'` mean the kcat source, does `'standard'` mean the kcat itself, or the enzyme, kcat and molecular weight as a whole?

**Comment by ae-tafur** [comment]
I agree. 

> Given that `'brenda'` and` 'dlkcat'` mean the kcat source, does` 'standard'` mean the kcat itself, or the enzyme, kcat and molecular weight as a whole?

It means the kcat itself
