### ISSUE TITLE
Error in minimizing protein pool usage

### ISSUE THREAD

**Issue by Yu-sysbio** [SysBioChalmers/GECKO#287]
https://github.com/SysBioChalmers/GECKO/blob/70b93d33aa5aefddeef2957c355046534a6b1ee6/protocol.m#L237

Should it be 1? The flux of prot_pool_exchange is negative.

**Comment by ae-tafur** [comment]
Yes, now flux is negative it must be positive

**Comment by edkerk** [comment]
Solved in 05df8105e61da016fb4d224834c7f1be0e914f97

**Comment by Yu-sysbio** [comment]
> Solved in [05df810](https://github.com/SysBioChalmers/GECKO/commit/05df8105e61da016fb4d224834c7f1be0e914f97)

Actually there are a few lines containing `-1` that should be corrected in the `protocol.m` file.
And let's keep in mind correcting this in the protocol manuscript.
