### ISSUE TITLE
work with multiple models in one MATLAB session

### ISSUE THREAD

**Issue by HossFir** [SysBioChalmers/GECKO#298]
I am trying to reconstruct two ecModels. However, when I change the directory to the new geckoroot directory, the ModelAdapter parameters show the old one, even though I am in the new GECKO directory!

https://github.com/SysBioChalmers/GECKO/blob/4b2a7e47f62579a90b973a75aefd692416a4aa3f/protocol.m#L37

**Comment by edkerk** [comment]
Note that in contrast to GECKO2, for GECKO3 you should not have multiple GECKO installations.

Instead, you might have multiple folders in `userData` (or elsewhere), one for each model. Each of those have a unique ModelAdapter file. If you want to start working on another GECKO model, you just need to specify the path to that model's folder location:

To start working on ecYeastGEM, which in this example is located in `GECKO\userData\ecYeastGEM`:
```matlab
 ModelAdapterManager.setDefaultAdapterFromPath(fullfile(geckoRoot,'userData','ecYeastGEM'));
```

Now the default adapter is set to ecYeastGEM, so any further GECKO functions will use the parameters from that model adapter and the data files in its subfolders.

If you want to start working on your own favourite organism, for which you have defined the appropriate subfolders and model adapter (*) at `C:\Work\ecModels\favourite_organism`:
```matlab
 ModelAdapterManager.setDefaultAdapterFromPath('C:\Work\ecModels\favourite_organism');
```

Similar as before, now GECKO will use settings and data from the new location.

(*) To define the appropriate subolders and model adapter, see `userData/yourModel`.

**Comment by HossFir** [comment]
Thank you very much for your comment! It worked!
