### ISSUE TITLE
applyCustomKcats with customKcats structure input

### ISSUE THREAD

**Issue by adimadkaikar** [SysBioChalmers/GECKO#303]
### Description of the bug:
 Unable to add custom kcats when I provide a struct as an argument to applyCustomKcats. The command fails on line 59 of applyCustomKcats as it expects the arguement to be a string or a vector. 

#### Reproducing these results:

```matlab
[ecModel, rxnUpdated, notMatch] = applyCustomKcats(ecModel, customKcats);
```

#### System information

* Operating system: Ubuntu 22.04.2LTS
* MATLAB version: 2022b
* GECKO version: 3.0

**I hereby confirm that I have:**
- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/GECKO) for running GECKO
- [x] Done this analysis in the `main` branch of the repository
- [x] Checked that a similar issue does not exist already

**Comment by edkerk** [comment]
Could you please check if the fix in #304 resolves this for you?
