### ISSUE TITLE
protocol for ecEcoli, and GECKO light protocol for Human-GEM

### ISSUE THREAD

**Issue by edkerk** [SysBioChalmers/GECKO#314]
### Description of the new feature:
- [ ] Somewhat similar to the [file](https://github.com/SysBioChalmers/GECKO/blob/chore/restructure-tutorials/tutorials/tutorial_yeast-GEM/protocol.m) in `tutorials_yeast-GEM`, a `protocol.m` should be written that details the reconstruction process of a GECKO light model. It could include comments only for the GECKO light specific commands and peculiarities, comments that are true for all of GECKO can be found in the `tutorials_yeast-GEM` example.

~- [ ] Minimal `protocol.m` for EcEcoli (full GECKO), based on stage 1-3 in the yeast-GEM tutorial. This protocol.m would only have comments for _E. coli_ specific matters.~

**Comment by Yu-sysbio** [comment]
I am glad to make an E. coli protocol but the revision now does not mention any addition of E. coli. Is this E. coli protocol high priority? @edkerk

**Comment by mihai-sysbio** [comment]
I believe PR #319 resolved this issue by setting up a tutorial for a full GECKO for yeast-GEM and a light GECKO for Human-GEM, so I'll go ahead and close it. Please reopen if needed.
