### ISSUE TITLE
RAVEN version

### ISSUE THREAD

**Issue by Yu-sysbio** [SysBioChalmers/GECKO#324]
https://github.com/SysBioChalmers/GECKO/blob/a3a9154966efb59096cf9d987effeb9474e4526b/tutorials/full_ecModel/protocol.m#L26

The latest version of RAVEN is only 2.8.2

**Comment by edkerk** [comment]
This is in preparation for the [2.8.3](https://github.com/SysBioChalmers/RAVEN/milestone/23) release that really is required, and can be released later today.

**Comment by mihai-sysbio** [comment]
Another to-do is to updated the self-hosted runner so that we get back the useful PR comments.

**Comment by edkerk** [comment]
RAVEN 2.8.3 is released, and it seems from a recent PR #331 that the GitHub Action is working well.

**Comment by mihai-sysbio** [comment]
That's actually surprising, since I didn't have a chance to bump up RAVEN in the GH runner, so I don't really know why the action is working.

**Comment by mihai-sysbio** [comment]
> That's actually surprising, since I didn't have a chance to bump up RAVEN in the GH runner, so I don't really know why the action is working.

Ah, now I know why - the action automatically fetches the latest release 💪🏻 so as soon as the new release was available, the GECKO test workflow worked as expected. I'm so glad it did.
