### ISSUE TITLE
Error running makeEcModel in full_ecModel protocol

### ISSUE THREAD

**Issue by Yu-sysbio** [SysBioChalmers/GECKO#329]
https://github.com/SysBioChalmers/GECKO/blob/38b6768b2ef9fb801a6739ef653372c3766c9f5a/tutorials/full_ecModel/protocol.m#L80

> Error using dispEM
> metsToAdd.metCharges must have the same number of elements as metsToAdd.mets
> Error in addMets (line 247)
>         dispEM(EM);
> Error in makeEcModel (line 340)
>     model = addMets(model,proteinMets);

**Comment by edkerk** [comment]
Should be already fixed in https://github.com/SysBioChalmers/GECKO/pull/328?

**Comment by Yu-sysbio** [comment]
> Should be already fixed in #328?

Oh sorry I missed it
