### ISSUE TITLE
enzyme usage unit

### ISSUE THREAD

**Issue by HossFir** [SysBioChalmers/GECKO#376]
https://github.com/SysBioChalmers/GECKO/blob/afa233429fe17f0a341f2ec8886fd6364fa94094/src/geckomat/utilities/enzymeUsage.m#L5

For consistency with the proteomics data, the absolute usage should be expressed in `mg/gDW`, as the proteomics data has this unit. The absolute usage is then multiplied by `kcat/mw` to convert the unit to `mmol/gDW/hr`!

**Comment by edkerk** [comment]
The `enzymeUsage` function is directly reporting the flux value from the enzyme usage reactions, so in mg/gDCW. The function documentation is just incorrect, while change that line to mention `mg/gDCW` instead.
