### ISSUE TITLE
`runDLKcat()`: _pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by edkerk** [SysBioChalmers/GECKO#396]
### Description of the bug:
When running `runDLKcat();` the following error is thrown:~
```python
Traceback (most recent call last):
  File "//DLKcat.py", line 26, in <module>
    fingerprint_dict = load_pickle('input/fingerprint_dict.pickle')
  File "//DLKcat.py", line 24, in load_pickle
    return pickle.load(f)
_pickle.UnpicklingError: invalid load key, 'v'.
``` 
#### Reproducing these results:
Probably only occurs if GECKO is cloned as `git` repository, not when downloaded as zip or installed as MATLAB Add-On.

However, the problem is not reproducible.

#### Solution:
~The error suggests that something is wrong with the file, but the underlying problem might be [`git lfs`](https://stackoverflow.com/a/67141340).~

~What **solved this for me** was to:~
~1. Delete the `src/dlkcat_gecko/input/fingerprint_dict.pickle` file.~
~2. Run `git restore .` (or actually, I did "Discard changes ..." in my git GUI client), to bring back the file.~
~3. There was no need to (re)install `git lfs` or re-clone the repository.~

#### System information

* Operating system: Windows 10
* MATLAB version: 2024a (probably irrelevant)
* GECKO version: 3.2.2
* RAVEN version: 2.10.1 (probably irrelevant)

#### I hereby confirm that:

- [x] My GECKO installation met [all requirements](https://github.com/SysBioChalmers/GECKO#required-software).
- [x] This bug occurs in the `main` branch of the repository.
- [x] A similar [issue](https://github.com/SysBioChalmers/GECKO/issues) does not already exist.

**Comment by edkerk** [comment]
Probably related to #393, will include there.

**Comment by mihai-sysbio** [comment]
Hmm @edkerk are we leaving the ARM64 issue open then - or is this issue more general, applicable to all new Docker images?

**Comment by edkerk** [comment]
1. The problem described here is a consequence of the `0.1-multiarch` container, so it makes sense to keep the discussion of this in #393.
2. The solution I initially thought I had found, as mentioned in the first post of this Issue, did not work. So IMHO this Issues should remain closed and inactive.
