### ISSUE TITLE
scaling of gecko model

### ISSUE THREAD

**Issue by hredestig** [SysBioChalmers/GECKO#4]
without a directly reproducible example, I note that upper bounds for protein draw reactions are often very small. With both cplex and glpk I have noted that this causes numerical instability, switching between growth and no-growth randomly. Have you also noted this @BenjaSanchez ? Have you experimented with scaling the problem?

**Comment by BenjaSanchez** [comment]
Hi @hredestig! I rarely get numerical instability with Gurobi. How often did you see this issue? Scaling could solve the issue if it presents often, by increasing let's say by 1e6 both the UB and the coefs in the S matrix related to enzymes. Any thoughts on this @Midnighter?

**Comment by hredestig** [comment]
for the cases I looked it was very frequent but I didn't try gurobi. I would have thought the solver would take care of this itself but perhaps need to be activated..

**Comment by Midnighter** [comment]
I have no immediate thoughts on this issue. I will run the Python package on the 1st release model as you suggested in #1 and see if I run into any of these issues.

**Comment by BenjaSanchez** [comment]
Great! Do let me know if you see this issue pop up again. Will leave it open for now.

**Comment by edkerk** [comment]
This scaling is included in GECKO3.
