### ISSUE TITLE
Problem with gene IDs that use the '-' character

### ISSUE THREAD

**Issue by BenjaSanchez** [SysBioChalmers/GECKO#5]
The [SGD notation](http://seq.yeastgenome.org/help/community/nomenclature-conventions#orf) for new genes that uses the `-X` format, where X can be any letter, is not compatible with the `writeCbModel` function of COBRA, as the character `-` is not properly parsed into the SBML file. For now, every `-` has been replaced with an `_` (for instance, gene #202 is `YDR322C_A`). However this is not ideal and hopefully COBRA should fix their parser.

**Comment by BenjaSanchez** [comment]
EDIT: moved this issue to the yeast7 repo as it should be solved there first

**Comment by BenjaSanchez** [comment]
As the COBRA saving function is now compatible with the `-` symbol, this issue has been fixed in commit [`0415224`](https://github.com/SysBioChalmers/GECKO/commit/0415224fa593cad8778a513d63dd482de5be52ad)

**Comment by Midnighter** [comment]
As a side note, I want to make sure that this also works in cobrapy. @BenjaSanchez can you let me know when a corresponding SBML file is available for testing, please?

**Comment by BenjaSanchez** [comment]
@Midnighter you can try it already with the available SBML file, let me know how it goes. There are still some issues that pop-up in http://sbml.org/validator/ that I will try to fix asap, you can follow those in issue #6
