### ISSUE TITLE
fix sbml errors

### ISSUE THREAD

**Issue by BenjaSanchez** [SysBioChalmers/GECKO#6]
When using http://sbml.org/validator/ on the ecYeast7 sbml file, 50 errors appear of the sort:

_Error (SBML Validation Rule #fbc-20303): The value of attribute 'fbc:chemicalFormula' on the SBML <species> object must be set to a string consisting only of atomic names or user defined compounds and their occurrence. Reference: L3V1 Fbc V2 Section 3.4 Encountered '(' when expecting a capital letter._

**Comment by BenjaSanchez** [comment]
As the warning states, symbols of the sort `()` are not compatible with the fbc:chemicalFormula field in SBML. This seems to be a problem of libSBML itself so not much can be done to fix it. However, as chemical formulas of metabolites are not used in ecModels, in commit [`109b620`](https://github.com/SysBioChalmers/GECKO/commit/109b620d248ca58bd3e7eb218e4d4aa77c6bd344) any `()` appearance has been removed. The model is now free of these errors when tested in  http://sbml.org/validator/. New errors having to do with gene associations appeared which will be fixed ASAP.

**Comment by BenjaSanchez** [comment]
The new errors that appear now are 539 of the following:

_Error: The attribute 'fbc:geneProduct' on a <GeneProductRef> if set, must refer to 'id' of a <GeneProduct> in the <Model>._

And 6511 of the following:

_Error: A <GeneProductAssociation> object must have one and only one of the concrete <Association> objects: <GeneProductRef>, <And> or <Or>._

Which means that all 7050 gene-reaction rules are incoherent with SBML format.

**Comment by BenjaSanchez** [comment]
Partially fixed: some previous gene rules were remaining which were not connected to any gene in `model.genes`, which created the first error of the 2 detected. In commits [`ca65d28`](https://github.com/SysBioChalmers/GECKO/commit/ca65d286b44b4a17e0ccc08c4204c5598da9ac09) and [`074677a`](https://github.com/SysBioChalmers/GECKO/commit/074677a3f3fc288452cd717ab8a05ad3588107f0) gene rules were fixed to properly represent the enzyme-constrained model: metabolic rxns now have no gene association, and only the enzyme exchange/draw reactions have a 1-1 gene association. When now tested in http://sbml.org/validator/, only the second error of the previously mentioned ones appear, for 5981 reactions (all rxns with no gene association):

_Error: A \<GeneProductAssociation\> object must have one and only one of the concrete \<Association\> objects: \<GeneProductRef\>, \<And\> or \<Or\>._

**Comment by BenjaSanchez** [comment]
Issue completely fixed in commit [`908b96d`](https://github.com/SysBioChalmers/GECKO/commit/908b96de791a6122f830c4159019be157fe7a55f): After saving the SBML file with COBRA, it is inmediately parsed to remove all lines that include `<fbc:geneProductAssociation/>`. This solution is not ideal and hopefully COBRA will change this in their saving function, but for now this will do. When tested both SBML files (`ecYeast` and `ecYeast_batch`) in http://sbml.org/validator/, no problems arise. @Midnighter please let me know if the python section is properly working now.

**Comment by Midnighter** [comment]
Both models can now be imported in cobrapy and the tests put in place by Henning pass. :smiley:
