### ISSUE TITLE
Potential incorrect reaction in ecYeastGEM

### ISSUE THREAD

**Issue by johanbj** [SysBioChalmers/GECKO#74]
Could somebody please double check the reaction catalysed by enzyme P07702 (Lys2). Compared to uniprot and SGD, I believe that the reaction in ecYeastGEM is incorrect.

Best regards

**Comment by johanbj** [comment]
Please, also, check protein P04173 (Leu2).
If Leu2 is indeed the incorrect reaction, could somebody advice me on how to get the cat-value for this enzyme in the reaction it catalyses in leucine biosynthesis. I seem to have difficulties finding it myself.

Thanks in advance

**Comment by edkerk** [comment]
Related to yeast-GEM, not GECKO.
