### ISSUE TITLE
Reproducability of figures in paper

### ISSUE THREAD

**Issue by Lottedegraaf** [SysBioChalmers/GECKO#77]
When I try to reproduce the figures from the paper (3A & 4B) with the model provided in GECKO toolbox 1.0.0 (ecYeast7_v1.0_batch.mat) following the supplementary information, my result doesn't match. For figure 3A, the result showed too high growth rates compared to the plot in the paper for almost all substrate metabolites, except mannose and fructose. For those two metabolites, the predicted growth rate is too high. For figure 4B, the result was approximately the same as in the paper. However, the result did not show acetate production. I attached the files I used. 
[plot 4B.zip](https://github.com/SysBioChalmers/GECKO/files/3397880/plot.4B.zip)
[plot 3A.zip](https://github.com/SysBioChalmers/GECKO/files/3397881/plot.3A.zip)

**Comment by IVANDOMENZAIN** [comment]
Hi Lotte, Thanks for sharing your code, we appreciate collaborating in this way. I didn't understand so well how the problem regarding `figure 4B` was posed, However I've noticed that you're blocking the facilitated transport reactions for mannose and fructose in your code. In the [supplementary material](https://www.embopress.org/action/downloadSupplement?doi=10.15252%2Fmsb.20167411&file=msb167411-sup-0001-Appendix.pdf) of the paper is said that this sugars facilitated transport was allowed for batch simulations. However, accorging to Boles and Hollenberg [1997](https://academic.oup.com/femsre/article/21/1/85/551032), fructose-proton symport systems have been described in other yeasts but not found in _S. cerevisiae_, therefore the facilitated reactions should be open but without any H+ transport coupling. With this I mean something like the following:

`%For growth on fructose and mannose the transport takes place in a passive
%way. [Boles & Hollenberg, 1997]
if strcmp(c_source,'D-fructose exchange (reversible)')
    model.S(strcmp(model.mets,'s_0796'),strcmp(model.rxns,'r_1134')) = 0;
    model.S(strcmp(model.mets,'s_0794'),strcmp(model.rxns,'r_1134')) = 0;
elseif strcmp(c_source,'D-mannose exchange (reversible)')
    model.S(strcmp(model.mets,'s_0796'),strcmp(model.rxns,'r_1139')) = 0;
    model.S(strcmp(model.mets,'s_0794'),strcmp(model.rxns,'r_1139')) = 0;
end`

As you might see, we just change the stoichometry of the reaction (no H+ present) but not its bounds.

**Comment by IVANDOMENZAIN** [comment]
Here you have an old script that we were using for batch simulations some time ago.

[changeMedia_batch.m.zip](https://github.com/SysBioChalmers/GECKO/files/3416498/changeMedia_batch.m.zip)

**Comment by Lottedegraaf** [comment]
Hi @IVANDOMENZAIN, Thank you for your help. I do see know that I switched the names of the two figures, so that was possibly why you did not understand the problem. The comment about the fructose and mannose transport helped, I could now reproduce figure 4B. However, I still have a different result for figure 3A (the chemostat experiment). My result is quite the same as in the paper, however, I don't have any acetate production (my files are in plot 3A.zip). Do you also have an explanation for that?

**Comment by BenjaSanchez** [comment]
@Lottedegraaf sorry for the big delay in the reply, I am slowly getting back to work things. In case you still need this, I will asap upload to the repo a branch with several scripts for reproducing exactly the figures of the paper. It will include the batch and chemostats studies. Will let you know through here when that happens

**Comment by edkerk** [comment]
Closed for being inactive for > 3 years.
