### ISSUE TITLE
feat: better documentation + example with proteomics integration

### ISSUE THREAD

**Issue by BenjaSanchez** [SysBioChalmers/GECKO#87]
Areas where we should improve documentation, as raised by @edkerk in a previous issue:
- [ ] Clarify what the input and output parameters refer to for each function.
- [x] Clarify the difference between `ecModel` and `ecModel_batch`.
- [x] Provide example of an `ecModel` constrained with proteomics data.

@IVANDOMENZAIN feel free to edit and add more.

**Comment by edkerk** [comment]
Addressed in GECKO3 protocol
