### ISSUE TITLE
Report Kcat matching

### ISSUE THREAD

**Issue by sulheim** [SysBioChalmers/GECKO#92]
Information on how accurately the Kcat-values extracted from BRENDA is matched to the chosen organism is important metadata. 

While it is possible to get this information by running run lines 36-50 of `enhanceGEM.m` and inspect the kcats variable it would be nice to just print out this information when running the pipeline. Along with this there is a need to update the docstring of `matchKcats` to explain the `wc-variables`.

**Comment by edkerk** [comment]
This is now implemented in GECKO3 `fuzzyKcatMatching`, with `wildCardLvl` and `origin` reported for each selected kcat, and explanations of their meaning.
