### ISSUE TITLE
SOAPpy.Errors.HTTPError: <HTTPError 302 Found> 

### ISSUE THREAD

**Issue by aszel** [SysBioChalmers/GECKO#99]
When calling the script "retrieveBRENDA.py" it returns an HTTP error. It seems something has changed on the other end. Or am I doing something wrong? Cannot see any problems within the script itself.

**Comment by BenjaSanchez** [comment]
@aszel hi there! there is an issue were this has been already raised (https://github.com/SysBioChalmers/GECKO/issues/78). The issue has been solved in the development branch of GECKO, so if you want to avoid it please switch locally to that branch, or alternatively await a new release in the coming week. Also, feel free to comment on that issue if the solution does not work for you.
